### PR TITLE
Modified checkKey field type to match generated proto3 go code

### PR DESCRIPTION
**Pull request by arogozin**
## What does this PR do/Why?
This PR updates `key` field type in `checkKey`  to match generated code for `proto3` syntax.

## Changelog
* checkKey.key type modified to match generated code for `proto3  syntax

## Notes to reviewers
`make proto` generates code that will throw error:
```
./healthchecks.go:52:9: invalid map key type checkKey
./healthchecks.go:82:16: invalid map key type checkKey
```

This is due to field type mismatch during the update of proto file to `proto3` syntax.

### CODE REVIEW

**Comment by alangibson01** [comment]
@arogozin Thank-you very much for this contribution. The Travis build shows that a couple of the end-to-end tests have problems:

```
e2e/api/api_test.go:451:37: too few values in &wrappers.UInt32Value literal
e2e/api/api_test.go:458:37: too few values in &wrappers.UInt32Value literal
```

Could you take a look at those, please?

**Comment by arogozin** [comment]
@ alangibson01 modified end-to-end tests to work with the proto3 upgrade!

**Comment by arogozin** [comment]
@alangibson01 modified end-to-end tests to work with the proto3 upgrade.

**Comment by jsravn** [comment]
@alangibson01 it looks like there is an erroneous status check in the build settings. It should only be checking for the PR build.

**Pull request merged**
